### PR TITLE
Made text smaller when the page is at a certain size

### PR DESCRIPTION
**Pull request by MedgerH**

### CODE REVIEW

**Comment by gannont14** [comment]
sure dude

**Comment by jul1anpa** [comment]
The text is still not formatted correctly on certain widths.

**Comment by jul1anpa** [comment]
But you guys already merged and closed the branch

**Comment by jul1anpa** [comment]
Unbelievable

**Comment by gannont14** [comment]
MAKE A NEW ONE MEDGER

**Comment by MedgerH** [comment]
It wasnt me it was this guy gannon

**Comment by gannont14** [comment]
bro didn't test before he commited

**Comment by gannont14** [comment]
i had faith in you

**Comment by jul1anpa** [comment]
L Medger

**Comment by MedgerH** [comment]
Arguing in a git pull request is a new low for you gannon

**Comment by gannont14** [comment]
this type of QA is NOT acceptable

**Comment by gannont14** [comment]
bro changed two lines, didn't test it, submitted a PR

**Comment by MedgerH** [comment]
I tried :( i am sorry

**Comment by gannont14** [comment]
it is okay brother, give it another rip

**Pull request merged**
